name: FastAPI CI/CD

on:
  #Trigger the workflow on push
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python

        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python venv
        run: pip3 install virtualenv

      - name: Virtual ENV
        uses: actions/cache@v2
        id: cache-env
        with:
          path: env
          key: ${{ runner.os }}-env-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: /
            ${{ runner.os }}-env-

      - name: Activate Virtual ENV
        run: python3 -m env && source env/bin/activate && pip3 install -r requirements.txt 

      - name: Run tests
        run: . env/bin/activate && pytest

      - name: Create archive of dependencies
        run: /
          cd ./env/lib/python3.8/site-packages
          zip -r9 ../../../../api.zip .

      - name: Add API files to zip files
        run: cd ./api && zip -g ../api.zip -r .
      - name: Upload zip file to artifact

        uses: actions/upload-artifact@v2
        

